OurWeddingSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import IndexView, AboutUsView, GalleryView, GiftListView, MessageFormView, RSVPFormView, BridalShowerGiftListView


app_name = 'home'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('sobre-nos/', AboutUsView.as_view(), name='about_us'),
    path('galeria/', GalleryView.as_view(), name='gallery'),
    path('presentes/', GiftListView.as_view(), name='gift_list'),
    path('cha-de-panela/', BridalShowerGiftListView.as_view(), name='bridal_shower_gift_list'),
    path('message/', MessageFormView.as_view(), name='message_form'),
    path('confirmar-presenca/', RSVPFormView.as_view(), name='rsvp'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html style="font-size: 16px;" lang="pt-BR">

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">

    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-NCR2LXZW7L"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'G-NCR2LXZW7L');
    </script>

    <meta name="keywords" content="Ideia de casamentos, Casamento  moderno, Cerimônia de casamento, Entre em contato conosco">
    {% if settings.logo %}
    <link rel="shortcut icon" href="{{ settings.logo.url }}" type="image/x-icon">
    {% endif %}
    <link rel="stylesheet" href="{% static 'home/css/nicepage.css' %}" media="screen">
    <link rel="stylesheet" href="{% static 'home/css/index.css' %}" media="screen">
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <script class="u-script" type="text/javascript" src="{% static 'home/scripts/nicepage.js' %}" defer=""></script>
    <meta name="generator" content="Nicepage 6.16.5, nicepage.com, Django 5.1.1">
    <meta name="referrer" content="origin">
    <link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Playfair+Display:400,400i,500,500i,600,600i,700,700i,800,800i,900,900i|Open+Sans:300,300i,400,400i,500,500i,600,600i,700,700i,800,800i">
    <link id="u-page-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Playfair+Display:400,400i,500,500i,600,600i,700,700i,800,800i,900,900i">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <meta name="theme-color" content="#d4b6be">
    <meta property="og:type" content="website">
    <meta name="description" content="{{ settings.site_description }}">
    <meta property="og:description" content="{{ settings.site_description }}">
    <meta property="og:locale" content="pt_BR">
    <meta property="og:title" content="{{ settings.couple_name }}">
    <meta property="og:site_name" content="{{ settings.couple_name }}">
    <link rel="canonical" href="{{ request.scheme }}://{{ request.get_host }}">
    <meta property="og:url" content="{{ request.scheme }}://{{ request.get_host }}">
    {% if settings.site_image %}
    <meta property="og:image" content="{{ request.scheme }}://{{ request.get_host }}{{ settings.site_image.url }}">
    {% endif %}
    <meta property="og:image:type" content="image/png">
    <meta property="og:image:width" content="1200">
    <meta property="og:image:height" content="630">
    <link rel="author" href="https://leonardocosta.dev/">
    {% if settings.site_image %}
    <link rel="icon" type="image/png" href="{{ settings.logo.url }}" sizes="16x16">
    {% endif %}
    {% block extra_head %}{% endblock extra_head %}
</head>

<body class="u-body u-xl-mode">
    <div id="loader">
        <div class="spinner-border text-primary" role="status">
            <span class="visually-hidden">Carregando...</span>
        </div>
    </div>

    <div id="page-content" style="display: none;">
        <header class="u-clearfix u-header u-header " id="sec-4a91">
            <nav class="navbar navbar-expand-lg navbar-light bg-light px-md-5">
                <div class="container-fluid">
                    <a class="navbar-brand" href="{% url 'home:index' %}">
                        {% if settings.logo %}
                            <img src="{{ settings.logo.url }}" alt="Logo" style="width: 70px;">
                        {% else %}
                            <h4 class="m-0">Logo</h4>
                        {% endif %}
                    </a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav ms-auto">
                            {% url 'home:index' as home_url %}
                            <li class="nav-item me-3">
                                <a class="nav-link {% if request.path == home_url %}active{% endif %}" aria-current="page" href="{{ home_url }}">Página Inicial</a>
                            </li>
                            {% if not settings.hide_rsvp %}
                                {% url 'home:rsvp' as rsvp_url %}
                                <li class="nav-item me-3">
                                    <a class="nav-link {% if request.path == rsvp_url %}active{% endif %}" href="{{ rsvp_url }}">Confirmar Presença</a>
                                </li>
                            {% endif %}
                            {% if not settings.hide_gifts %}
                                {% url 'home:gift_list' as gift_list_url %}
                                <li class="nav-item me-3">
                                    <a class="nav-link {% if request.path == gift_list_url %}active{% endif %}" href="{{ gift_list_url }}">Lista de Presentes</a>
                                </li>
                            {% endif %}
                            {% if not settings.hide_bridal_shower_gift %}
                                {% url 'home:bridal_shower_gift_list' as bridal_shower_gift_list_url %}
                                <li class="nav-item me-3">
                                    <a class="nav-link {% if request.path == bridal_shower_gift_list_url %}active{% endif %}" href="{{ bridal_shower_gift_list_url }}">Chá de Panela</a>
                                </li>
                            {% endif %}
                            {% if not settings.hide_gallery %}
                                {% url 'home:gallery' as gallery_url %}
                                <li class="nav-item me-3">
                                    <a class="nav-link {% if request.path == gallery_url %}active{% endif %}" href="{{ gallery_url }}">Galeria</a>
                                </li>
                            {% endif %}
                            {% if not settings.hide_about_us %}
                            {% url 'home:about_us' as about_us_url %}
                            <li class="nav-item">
                                <a class="nav-link {% if request.path == about_us_url %}active{% endif %}" href="{{ about_us_url }}">Sobre Nós</a>
                            </li>
                            {% endif %}
                            {% if request.user.is_authenticated %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'admin:index' %}">Administração</a>
                                </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>
            
        </header>

        <main class="container-fluid p-0">
            
            {% if messages %}
                <div class="position-absolute start-50 translate-middle-x mt-3" style="z-index: 1050; width: 100%; max-width: 600px; top: 4rem;">
                {% for message in messages %}
                <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} alert-dismissible fade show" role="alert">
                    <strong>{% if message.tags == 'success' %}Oba!{% else %}Ops!{% endif %}</strong> {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
                </div>
            {% endif %}
            
            {% block content %}{% endblock content %}
        </main>

        <footer class="u-align-center u-clearfix u-container-align-center u-footer u-grey-80 u-footer" id="sec-548a">
            <div class="u-clearfix u-sheet u-sheet-1">
                <p class="u-small-text u-text u-text-variant u-text-1">{{ footer.content }}</p>
            </div>
        </footer>
        <section class="u-backlink u-clearfix u-grey-80">
            <p class="u-text">
                <span>Site criado por <a class="u-link text-pink" href="https://leonardocosta.dev/" target="_blank">Leonardo Costa</a> com o design de </span>
                <a class="u-link text-pink" href="https://nicepage.com/" target="_blank" rel="nofollow">
                    <span>Nicepage</span>
                </a>.
            </p>
        </section>
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    {% if settings.song %}
        <audio id="background-audio" loop>
            <source src="{{ settings.song.url }}" type="audio/mp3">
            Seu navegador não suporta o elemento <code>audio</code>.
        </audio>
        <button class="floating-button" id="audio-control-button">
            ▶️
        </button>
    {% endif %}
    {% if user.is_staff %}
    <script>
    document.addEventListener('DOMContentLoaded', function() {
        var elements = document.querySelectorAll('[data-text-url]');
        elements.forEach(function(element) {
        element.addEventListener('dblclick', function() {
            var url = this.getAttribute('data-text-url');
            if (url) {
            window.location.href = url;
            }
        });
        });
    });
    </script>
    {% endif %}
    {% block extra_scripts %}{% endblock extra_scripts %}
    <script src="{% static 'home/scripts/scripts.js' %}"></script>
</body>

</html>